### ISSUE TITLE
Not sure what to put for the redirecturl for this Myuni Demo.

### ISSUE THREAD

**Issue by ChauncyYinXun** [docusign/sample-app-myuni-python#4]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/32704417/96726470-99e00a00-13e4-11eb-9a32-ec8e21c4fd87.png">

http://localhost:5001/api/code_grant_auth
{"reason":"Unauthorized","response":"Permissions should be granted for current integration","url":"https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20click.manage&client_id=a1797dec-d57f-42f3-9a46-671e9628ce2b&redirect_uri=http://localhost:3000/callback&state=9E15664D173F42C3BE7963CE1F45BAE0"}

I encountered this error when trying to login to an instance I set up. Is this an issue with a wrong redirect Url or is it an authentication issue? We have tried the following redirect url: 
1. http://localhost:5001/api
2. http://localhost:5001
3. http://localhost:3000
4. https://www.docusign.com/
5. https://webhook.site/cb505582-0ad2-4be3-9c06-9d204dc21e8b

**Comment by InbarGazit** [comment]
you need to add http://localhost:3000/callback to your IK , do you know how to do that?

**Comment by InbarGazit** [comment]
Sorry, I'll check if the README here is not clear on this topic.

**Comment by ChauncyYinXun** [comment]
Hi, @InbarGazit. Now it's working. Thank you!
